version: "2.1"
networks:
  movies:
    driver: bridge
services:
  mongo:
    image: tutum/mongodb
    environment:
      MONGODB_USER: "root"
      MONGODB_DATABASE: "movies"
      MONGODB_PASS: "password"
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db/:rw
    networks:
      - movies
  backend:
    build: .
    mem_limit: 200m
    command: "npm run dev"
    ports:
      - "4000:4000"
    env_file: ./.env
    volumes:
      - ./:/src/:rw
    depends_on:
      mongo:
        condition: service_started
    networks:
      - movies
  ship:
    image: portainer/portainer
    #mem_limit: 50m
    networks:
      - movies
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock