module.exports = {
    VALIDATION: 'VALIDATION',
    DUPLICATE_DOCUMENT: 'DUPLICATE_DOCUMENT',
    BAD_IMPLEMENTATION: 'BAD_IMPLEMENTATION',
    NOT_FOUND: 'NOT_FOUND',
    ACCESS_DENIED: 'ACCESS_DENIED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};